config/routes.rb
Rails.application.routes.draw do

  resources :events, only: [:index, :create, :edit, :update] do
    member do
      post 'attend_event'
      delete 'unattend_event'
      delete 'delete_event'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'events#index'
  # get 'new_event', to: 'events#index', as: 'new_event'
  post 'new_event', to: 'events#create', as: 'create_new_event'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendee, foreign_key: :attendee_id, class_name: 'User'
    belongs_to :attended_event, foreign_key: :attended_event_id, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, foreign_key: 'creator_id', class_name: 'User'
    has_many :attendances, foreign_key: :attended_event_id, class_name: 'Attendance'
    has_many :attendees, through: :attendances, source: :attendee 
    scope :past, ->{ where('date < ?', Date.today)}
    scope :upcoming, -> { where('date >= ?', Date.today) }

    def self.past(user)
        user.attended_events.where('date < ?', Date.today)
    end



    def self.upcoming(user)
        user.attended_events.where('date > ?', Date.today)
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendances, foreign_key: :attendee_id, class_name: 'Attendance'
  has_many :attended_events, through: :attendances, source: :attended_event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    # def create
        
    #     @event = Event.find(params[:event_id])
    #     @attendance = @event.attendances.build(attendee: current_user)
    #     if @attendance.save
    #         redirect_to event_path(@event), notice: 'You have successfully joined the event.'
    #     else
    #         redirect_to event_path(@event), alert: 'Unable to join the event.'
    #     end
    # end

    # def destroy
    #     @event = Event.find(params[:event_id])
    #     @attendance = @event.attendances.find_by(attendee: current_user)
    
    #     if @attendance.destroy
    #       redirect_to event_path(@event), notice: 'You have successfully left the event.'
    #     else
    #       redirect_to event_path(@event), alert: 'Unable to leave the event.'
    #     end
    # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!

    def index
        @events = Event.all
        @users = User.all
        @event = current_user.events.build
        @past_events = Event.past(current_user)
        @upcome_events = Event.upcoming(current_user)
    end

    def create
       @event = current_user.events.build(events_params)
       if @event.save
          redirect_to root_path
       else 
          @events = Event.all
          render :index
       end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])
        if @event.update(events_params)
            redirect_to root_path
        else
            render 'edit'
        end
    end

    def delete_event
        @event = Event.find(params[:id])
        current_user.attended_events.delete(@event)
        redirect_to events_path
    end
    
    def attend_event
        event = Event.find(params[:id])
        current_user.attended_events << event unless current_user.attended_events.include?(event)
        redirect_to events_path
      end
    
      def unattend_event
        event = Event.find(params[:id])
        current_user.attended_events.delete(event)
        redirect_to events_path
      end
    private

    def events_params
       params.require(:event).permit(:title, :date, :location, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<%= form_for(@event) do |form| %>
    <div class="title_field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="date_field">
      <%= form.label :date %>
      <%= form.datetime_select :date %>
    </div>
  
    <div class="desc_field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="location_field" >
    <%= form.label :location %>
    <%= form.text_field :location %>
    </div>
  
    <div class="action">
      <%= form.submit "Update event" %>
    </div>

<% end %>

app/views/events/index.html.erb
<% @users.each do |user| %>
  <h2><%= user.email %>'s Created Events:</h2>
  <ul>
     <% user.attended_events.each do |attended_event| %>
      <%= attended_event.creator.email %>
      <% if current_user.email == attended_event.creator.email %>
      <li><%= link_to attended_event.title, edit_event_path(attended_event) %> on <%= attended_event.date %></li>
      <%= button_to "Delete", delete_event_event_path(attended_event), method: :delete, data: { turbo: false } %>
      <% else %>
      <li><%=attended_event.title %> on <%= attended_event.date %></li>

      <p>Sorry you cannot edit this event</p>
      <%= button_to "Delete", delete_event_event_path(attended_event), method: :delete, data: { turbo: false } %>

      <% end %>
      <% end %>
      
  </ul>
  <% user.events.each do |event| %>
    <p>
      Title: <%= event.title %><br>
      Date: <%= event.date %><br>
      Location: <%= event.location %><br>
      Description: <%= event.description %><br>
      Attendees:
      <% event.attendees.each do |attendee| %>
        <%= attendee.email %>
      <% end %>
    </p>
    <% if current_user.attended_events.include?(event) %>
      <%= button_to 'Leave Event', unattend_event_event_path(event), method: :delete %>
    <% else %>
      <%= button_to 'Join Event', attend_event_event_path(event), method: :post %>
    <% end %>
    <hr>
  <% end %>
<% end %>


<%= form_with url: create_new_event_path, model: @event, local: true do |form| %>
    <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
        <ul>
          <% @event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="title_field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="date_field">
      <%= form.label :date %>
      <%= form.datetime_select :date %>
    </div>
  
    <div class="desc_field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>

    <div class="location_field" %>
    <%= form.label :location %>
    <%= form.text_field :location %>
    </div>
  
    <div class="action">
      <%= form.submit "Create event" %>
    </div>
  <% end %>
  
<h2>Your Attended Events</h2>

<h3>Your past Events</h3>

  <% @past_events.each do |past_event| %>
    <br>
    <%= past_event.title %> on <%= past_event.date %>
    Location: <%= past_event.location %>
  <% end %>

<h3>Your upcomeing Events</h3>
<% @upcome_events.each do |upcome_event| %>
  <br>
  <%= upcome_event.title %> on <%= upcome_event.date %>
  Location: <%= upcome_event.location %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>